export interface IDataTrips {
  title: string;
  data: ITrip[];
}
export interface ITrip {
  title: string;
  id: number;
  startDate: string;
  leadDriver: string;
  teamDriver: string;
  dispatchedBy: string;
  issuedOn: string;
}
export const DATATrips: IDataTrips[] = [
  {
    title: "Upcoming Trips",
    data: [
      {
        title: "Driver Trip Itinerary T00502",
        id: 1,
        startDate: "August 31, 2022 12:00 PM",
        leadDriver: "Chris Beard",
        teamDriver: "N/A",
        dispatchedBy: "Mike Estabrooks",
        issuedOn: "August 31, 2022 12:00 PM",
      },
    ],
  },
  {
    title: "Previous Trips",
    data: [
      {
        title: "Driver Trip Itinerary T00502",
        id: 2,
        startDate: "August 31, 2022 12:00 PM",
        leadDriver: "Chris Beard",
        teamDriver: "N/A",
        dispatchedBy: "Mike Estabrooks",
        issuedOn: "August 31, 2022 12:00 PM",
      },
      {
        title: "Driver Trip Itinerary T00502",
        id: 3,
        startDate: "August 31, 2022 12:00 PM",
        leadDriver: "Chris Beard",
        teamDriver: "N/A",
        dispatchedBy: "Mike Estabrooks",
        issuedOn: "August 31, 2022 12:00 PM",
      },
      {
        title: "Driver Trip Itinerary T00502",
        id: 4,
        startDate: "August 31, 2022 12:00 PM",
        leadDriver: "Chris Beard",
        teamDriver: "N/A",
        dispatchedBy: "Mike Estabrooks",
        issuedOn: "August 31, 2022 12:00 PM",
      },
      {
        title: "Driver Trip Itinerary T00502",
        id: 4,
        startDate: "August 31, 2022 12:00 PM",
        leadDriver: "Chris Beard",
        teamDriver: "N/A",
        dispatchedBy: "Mike Estabrooks",
        issuedOn: "August 31, 2022 12:00 PM",
      },
      {
        title: "Driver Trip Itinerary T00502",
        id: 4,
        startDate: "August 31, 2022 12:00 PM",
        leadDriver: "Chris Beard",
        teamDriver: "N/A",
        dispatchedBy: "Mike Estabrooks",
        issuedOn: "August 31, 2022 12:00 PM",
      },
      {
        title: "Driver Trip Itinerary T00502",
        id: 4,
        startDate: "August 31, 2022 12:00 PM",
        leadDriver: "Chris Beard",
        teamDriver: "N/A",
        dispatchedBy: "Mike Estabrooks",
        issuedOn: "August 31, 2022 12:00 PM",
      },
      {
        title: "Driver Trip Itinerary T00502",
        id: 4,
        startDate: "August 31, 2022 12:00 PM",
        leadDriver: "Chris Beard",
        teamDriver: "N/A",
        dispatchedBy: "Mike Estabrooks",
        issuedOn: "August 31, 2022 12:00 PM",
      },
      {
        title: "Driver Trip Itinerary T00502",
        id: 4,
        startDate: "August 31, 2022 12:00 PM",
        leadDriver: "Chris Beard",
        teamDriver: "N/A",
        dispatchedBy: "Mike Estabrooks",
        issuedOn: "August 31, 2022 12:00 PM",
      },
      {
        title: "Driver Trip Itinerary T00502",
        id: 4,
        startDate: "August 31, 2022 12:00 PM",
        leadDriver: "Chris Beard",
        teamDriver: "N/A",
        dispatchedBy: "Mike Estabrooks",
        issuedOn: "August 31, 2022 12:00 PM",
      },
      {
        title: "Driver Trip Itinerary T00502",
        id: 4,
        startDate: "August 31, 2022 12:00 PM",
        leadDriver: "Chris Beard",
        teamDriver: "N/A",
        dispatchedBy: "Mike Estabrooks",
        issuedOn: "August 31, 2022 12:00 PM",
      },
      {
        title: "Driver Trip Itinerary T00502",
        id: 4,
        startDate: "August 31, 2022 12:00 PM",
        leadDriver: "Chris Beard",
        teamDriver: "N/A",
        dispatchedBy: "Mike Estabrooks",
        issuedOn: "August 31, 2022 12:00 PM",
      },
      {
        title: "Driver Trip Itinerary T00502",
        id: 4,
        startDate: "August 31, 2022 12:00 PM",
        leadDriver: "Chris Beard",
        teamDriver: "N/A",
        dispatchedBy: "Mike Estabrooks",
        issuedOn: "August 31, 2022 12:00 PM",
      },
      {
        title: "Driver Trip Itinerary T00502",
        id: 4,
        startDate: "August 31, 2022 12:00 PM",
        leadDriver: "Chris Beard",
        teamDriver: "N/A",
        dispatchedBy: "Mike Estabrooks",
        issuedOn: "August 31, 2022 12:00 PM",
      },
      {
        title: "Driver Trip Itinerary T00502",
        id: 4,
        startDate: "August 31, 2022 12:00 PM",
        leadDriver: "Chris Beard",
        teamDriver: "N/A",
        dispatchedBy: "Mike Estabrooks",
        issuedOn: "August 31, 2022 12:00 PM",
      },
      {
        title: "Driver Trip Itinerary T00502",
        id: 4,
        startDate: "August 31, 2022 12:00 PM",
        leadDriver: "Chris Beard",
        teamDriver: "N/A",
        dispatchedBy: "Mike Estabrooks",
        issuedOn: "August 31, 2022 12:00 PM",
      },
      {
        title: "Driver Trip Itinerary T00502",
        id: 4,
        startDate: "August 31, 2022 12:00 PM",
        leadDriver: "Chris Beard",
        teamDriver: "N/A",
        dispatchedBy: "Mike Estabrooks",
        issuedOn: "August 31, 2022 12:00 PM",
      },
      {
        title: "Driver Trip Itinerary T00502",
        id: 4,
        startDate: "August 31, 2022 12:00 PM",
        leadDriver: "Chris Beard",
        teamDriver: "N/A",
        dispatchedBy: "Mike Estabrooks",
        issuedOn: "August 31, 2022 12:00 PM",
      },
      {
        title: "Driver Trip Itinerary T00502",
        id: 4,
        startDate: "August 31, 2022 12:00 PM",
        leadDriver: "Chris Beard",
        teamDriver: "N/A",
        dispatchedBy: "Mike Estabrooks",
        issuedOn: "August 31, 2022 12:00 PM",
      },
      {
        title: "Driver Trip Itinerary T00502",
        id: 4,
        startDate: "August 31, 2022 12:00 PM",
        leadDriver: "Chris Beard",
        teamDriver: "N/A",
        dispatchedBy: "Mike Estabrooks",
        issuedOn: "August 31, 2022 12:00 PM",
      },
      {
        title: "Driver Trip Itinerary T00502",
        id: 4,
        startDate: "August 31, 2022 12:00 PM",
        leadDriver: "Chris Beard",
        teamDriver: "N/A",
        dispatchedBy: "Mike Estabrooks",
        issuedOn: "August 31, 2022 12:00 PM",
      },
      {
        title: "Driver Trip Itinerary T00502",
        id: 4,
        startDate: "August 31, 2022 12:00 PM",
        leadDriver: "Chris Beard",
        teamDriver: "N/A",
        dispatchedBy: "Mike Estabrooks",
        issuedOn: "August 31, 2022 12:00 PM",
      },
      {
        title: "Driver Trip Itinerary T00502",
        id: 4,
        startDate: "August 31, 2022 12:00 PM",
        leadDriver: "Chris Beard",
        teamDriver: "N/A",
        dispatchedBy: "Mike Estabrooks",
        issuedOn: "August 31, 2022 12:00 PM",
      },
      {
        title: "Driver Trip Itinerary T00502",
        id: 4,
        startDate: "August 31, 2022 12:00 PM",
        leadDriver: "Chris Beard",
        teamDriver: "N/A",
        dispatchedBy: "Mike Estabrooks",
        issuedOn: "August 31, 2022 12:00 PM",
      },
      {
        title: "Driver Trip Itinerary T00502",
        id: 4,
        startDate: "August 31, 2022 12:00 PM",
        leadDriver: "Chris Beard",
        teamDriver: "N/A",
        dispatchedBy: "Mike Estabrooks",
        issuedOn: "August 31, 2022 12:00 PM",
      },
      {
        title: "Driver Trip Itinerary T00502",
        id: 4,
        startDate: "August 31, 2022 12:00 PM",
        leadDriver: "Chris Beard",
        teamDriver: "N/A",
        dispatchedBy: "Mike Estabrooks",
        issuedOn: "August 31, 2022 12:00 PM",
      },
      {
        title: "Driver Trip Itinerary T00502",
        id: 4,
        startDate: "August 31, 2022 12:00 PM",
        leadDriver: "Chris Beard",
        teamDriver: "N/A",
        dispatchedBy: "Mike Estabrooks",
        issuedOn: "August 31, 2022 12:00 PM",
      },
    ],
  },
];
